/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table level
	 */
	export class Level extends levelBase{

		//region Static
		//endregion


		//region Fields
        /**
         * Array de ubicaciones por nivel
         */
        public locations: Location[];

		//endregion


		//region Private Methods
		//endregion


		//region Events
		//endregion


		//region Properties
		//endregion

	}
}