/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table product
	 */
	export class Product extends productBase{

		//region Static
		//endregion


		//region Fields
		//endregion


		//region Private Methods
		//endregion


		//region Events
		//endregion


		//region Properties
		//endregion

	}
}