/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table rack
	 */
	export class Rack extends rackBase{

		//region Static
		//endregion


		//region Fields
        /**
		 * Array de niveles
         */
		public levels: Level[];
		//endregion


		//region Private Methods
		//endregion


		//region Events
		//endregion


		//region Properties
		//endregion

	}
}