<?php
/**
 * Stub generated by xlatte
 */
class Location extends locationBase{

    /**
     * Crear un nuevo registro de tipo Location con una cantidad inicial igual a cero para el nivel y producto
     * especificados en los parámetros.
     *
     * @param int $idlevel
     * @param int $idproduct
     * @return Location
     */
    public static function create($idlevel, $idproduct) {
        $location = new Location();
        $location->idlevel = $idlevel;
        $location->idproduct = $idproduct;
        $location->quantity = 0;
        $location->insert();

        return $location;
    }

    /**
     * Este método se ejecuta antes de realizar la inserción en la base de datos
     * - Registramos la fecha del sistema
     *
     * @return bool|void
     */
    public function onInserting() {
        $this->created = DL::dateTime();
    }

    /**
     * @override
     */
    public function onSaving() {
        $this->created = DL::dateTime();
    }
}