<?php
/**
 * Stub generated by xlatte
 */
class Product extends productBase{

    /**
     * Este método se ejecuta antes de realizar la inserción en la base de datos
     * - Registramos la fecha del sistema
     *
     * @return bool|void
     */
    public function onInserting() {
        $this->created = DL::dateTime();
    }
}